######### model parameter
models:
  model: RetrievalModel
  output_channels: 512
  pretrained: ./pretrained_models/resnet50-0676ba61.pth
  freeze_bn: True

#### dataset define
dataset:
  dataset_train: train
  dataset_val: val
  data_dir: ./data/VehID/images
  list_dir: ./data/VehID/split_list
  num_sample_per_id: 4
  # lmdb_dir: ./data/lmdb/VehID
  inst_blc: True
  resize: 256
  input_size: 224
  normal_mean:
    - 0.485
    - 0.456
    - 0.406
  normal_std:
    - 0.229
    - 0.224
    - 0.225

######### train parameter
training:
  save_dir: ./save/VehID
  experiment_id: xbm_contrastive_mem_6w
  ft: False
  losses:
    xbm_contrastive:
      loss_weight: 1
      loss_param:
        mem_size: 60000
        feat_dim: 512
        thres: 0.5
        num_sample_per_id: 4
        start_it: 30000
  optimizer:
    optim_method: adam
    lr: 0.00001
    lr_fc_mul: 1
    weight_decay: 0.0004
    lr_decay: 0.3
    lr_decay_iter:
      - 40000
      - 80000

  val_iter: 5000
  save_iter: 10000 # save a checkpoint
  max_iter: 100000
  log_interval: 100
  num_workers: 4
  batchsize: 224
  no_cuda: False
  seed: 42
  resume_train: none

######### evaluation parameter
evaluation:
  dataset:
    dataset_test: 
      - test_small
      - test_medium
      - test_large
    data_dir: ./data/VehID/images
    list_dir: ./data/VehID/split_list
    resize: 256
  recall_k:
    - 1
    - 5
  save_result: ./save/VehID/train/RetrievalModel/xbm_contrastive_mem_6w
  resume_eval: ./save/VehID/train/RetrievalModel/xbm_contrastive_mem_6w/best.pth.tar
