######### model parameter
models:
  model: RetrievalModel
  output_channels: 512
  pretrained: ./pretrained_models/resnet50-0676ba61.pth
  freeze_bn: True

#### dataset define
dataset:
  dataset_train: train
  dataset_val: val
  data_dir: ./data/SOP/images
  list_dir: ./data/SOP/split_list
  num_sample_per_id: 4
  # lmdb_dir: ./data/lmdb/SOP
  inst_blc: True
  resize: 256
  input_size: 224
  normal_mean:
    - 0.485
    - 0.456
    - 0.406
  normal_std:
    - 0.229
    - 0.224
    - 0.225

######### train parameter
training:
  save_dir: ./save/SOP
  experiment_id: auc_huber_sgd
  ft: False
  losses:
    auc_huber:
      loss_weight: 1
      loss_param:
        num_sample_per_id: 4
        temp: 0.1
  optimizer:
    optim_method: sgd
    lr: 0.003
    lr_fc_mul: 1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0004
    lr_decay: 0.3
    lr_decay_iter:
      - 20000
      - 40000

  val_iter: 2500
  save_iter: 10000 # save a checkpoint
  max_iter: 50000
  log_interval: 100
  num_workers: 4
  batchsize: 224
  no_cuda: False
  seed: 42
  resume_train: none

######### evaluation parameter
evaluation:
  dataset:
    dataset_test: test
    data_dir: ./data/SOP/images
    list_dir: ./data/SOP/split_list
    resize: 256
  recall_k:
    - 1
    - 10
    - 100
    - 1000
  save_result: ./save/SOP/train/RetrievalModel/auc_huber_sgd
  resume_eval: ./save/SOP/train/RetrievalModel/auc_huber_sgd/best.pth.tar
