######### model parameter
models:
  model: RetrievalModel
  output_channels: 512
  pretrained: ./pretrained_models/resnet50-0676ba61.pth
  freeze_bn: True

#### dataset define
dataset:
  dataset_train: train
  dataset_val: val
  data_dir: ./data/iNaturalist/images
  list_dir: ./data/iNaturalist/split_list
  num_sample_per_id: 4
  # lmdb_dir: ./data/lmdb/iNaturalist
  inst_blc: True
  resize: 256
  input_size: 224
  normal_mean:
    - 0.485
    - 0.456
    - 0.406
  normal_std:
    - 0.229
    - 0.224
    - 0.225

######### train parameter
training:
  save_dir: ./save/iNaturalist
  experiment_id: auc_huber_sgd
  ft: False
  losses:
    auc_huber:
      loss_weight: 1
      loss_param:
        num_sample_per_id: 4
        temp: 0.1
  optimizer:
    optim_method: sgd
    lr: 0.001
    lr_fc_mul: 2
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0004
    lr_decay: 0.3
    lr_decay_iter:
      - 80000
      - 110000

  val_iter: 5000
  save_iter: 10000 # save a checkpoint
  max_iter: 130000
  log_interval: 100
  num_workers: 4
  batchsize: 224
  no_cuda: False
  seed: 42
  resume_train: none

######### evaluation parameter
evaluation:
  dataset:
    dataset_test: test
    data_dir: ./data/iNaturalist/images
    list_dir: ./data/iNaturalist/split_list
    resize: 256
  recall_k:
    - 1
    - 4
    - 16
    - 32
  save_result: ./save/iNaturalist/train/RetrievalModel/auc_huber_sgd
  resume_eval: ./save/iNaturalist/train/RetrievalModel/auc_huber_sgd/best.pth.tar
